matrix:
  include:
    - dist: bionic
    - language: c
      install:
        #- set -v
        - export ARDUINO_IDE_VERSION="1.8.8"
        - wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
        - mkdir $HOME/arduino_ide
        - tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/ 
        - curl -fsSL https://www.pjrc.com/teensy/td_145/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
        - chmod +x TeensyduinoInstall.linux64
        - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
        - sleep 3
        - export DISPLAY=:1.0
        - ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
        #- $HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION/arduino --install-library "Adafruit ST7735 and ST7789 Library"
      script:
        #- $HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION/arduino --verify --verbose --board "teensy:avr:teensy36:usb=serial,speed=180,opt=o2std,keys=en-us" blink/blink.ino
        - source build-sketches.sh

notifications:
  email:
    on_success: change
    on_failure: change
